[build]
  publish = "."

[[redirects]]
  from = "/chat"
  to   = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/whisper"
  to   = "/.netlify/functions/whisper"
  status = 200

[[redirects]]
  from = "/tts"
  to   = "/.netlify/functions/tts"
  status = 200
